# frozen_string_literal: true

module Fhir
  class ExportController < BaseController
    before_action :authenticate_user!

    def bundle
      @account = current_account
      @measurements = @account.measurements.includes(:measurement_type).order(measurement_date: :desc)
      @diseases = @account.diseases.includes(:predefined_disease)
      @medications = @account.medications
      @treatments = @account.treatments.includes(:diseases)

      pdf = generate_health_report_pdf
      send_data pdf,
                type: "application/pdf",
                filename: "health_report_#{current_account.username}_#{Time.zone.today.iso8601}.pdf"
    rescue NoMethodError
      pdf = generate_health_report_pdf_fallback
      send_data pdf,
                type: "application/pdf",
                filename: "health_report_#{Time.zone.today.iso8601}.pdf"
    end

    def measurements
      measurements = current_account.measurements.includes(:measurement_type).order(measurement_date: :desc)
      pdf = generate_measurements_pdf(measurements)
      send_data pdf,
                type: "application/pdf",
                filename: "measurements_report_#{Time.zone.today.iso8601}.pdf"
    end

    def diseases
      diseases = current_account.diseases.includes(:predefined_disease)
      pdf = generate_diseases_pdf(diseases)
      send_data pdf,
                type: "application/pdf",
                filename: "diseases_report_#{Time.zone.today.iso8601}.pdf"
    end

    def medications
      medications = current_account.medications
      pdf = generate_medications_pdf(medications)
      send_data pdf,
                type: "application/pdf",
                filename: "medications_report_#{Time.zone.today.iso8601}.pdf"
    end

    def treatments
      treatments = current_account.treatments.includes(:diseases)
      pdf = generate_treatments_pdf(treatments)
      send_data pdf,
                type: "application/pdf",
                filename: "treatments_report_#{Time.zone.today.iso8601}.pdf"
    end

    private

    def generate_health_report_pdf_fallback
      account_name = @account.username
      measurements_table = measurements_table_data(@measurements)
      Prawn::Document.new do
        title_size = 24
        header_size = 16
        normal_size = 10

        bounding_box([0, cursor], width: 540) do
          text "Health Report", size: title_size, style: :bold, align: :center
          move_down 10
          text "Generated: #{Time.zone.today.strftime('%d %B %Y')}", size: normal_size, align: :center
          text "Patient: #{account_name}", size: normal_size, align: :center
          move_down 30
        end

        move_down 20

        bounding_box([0, cursor], width: 540) do
          text "Measurements", size: header_size, style: :bold
          move_down 10
          if @measurements&.any?
            table measurements_table, width: 540, cell_style: { size: normal_size } do
              style rows(0), style: :bold, background_color: "E8E8E8"
              style column(2), align: :right
            end
          else
            text "No measurements recorded.", size: normal_size, style: :italic
          end
        end

        move_down 30

        bounding_box([0, cursor], width: 540) do
          text "Diseases", size: header_size, style: :bold
          move_down 10
          if @diseases&.any?
            @diseases.each do |disease|
              text "• #{disease.predefined_disease.name} - #{disease.status}", size: normal_size
            end
          else
            text "No diseases recorded.", size: normal_size, style: :italic
          end
        end

        move_down 30

        bounding_box([0, cursor], width: 540) do
          text "Medications", size: header_size, style: :bold
          move_down 10
          if @medications&.any?
            @medications.each do |med|
              text "• #{med.name} - #{med.dosage} (#{med.frequency})", size: normal_size
            end
          else
            text "No medications recorded.", size: normal_size, style: :italic
          end
        end

        move_down 30

        bounding_box([0, cursor], width: 540) do
          text "Treatments", size: header_size, style: :bold
          move_down 10
          if @treatments&.any?
            @treatments.each do |treatment|
              text "• #{treatment.name}", size: normal_size
            end
          else
            text "No treatments recorded.", size: normal_size, style: :italic
          end
        end

        move_down 50
        text "Generated by Salus", size: 8, align: :center, style: :italic
      end.render
    end

    def generate_health_report_pdf
      account_name = @account.username
      measurements_table = measurements_table_data(@measurements)
      Prawn::Document.new do
        title_size = 24
        header_size = 16
        normal_size = 10

        bounding_box([0, cursor], width: 540) do
          text "Health Report", size: title_size, style: :bold, align: :center
          move_down 10
          text "Generated: #{Time.zone.today.strftime('%d %B %Y')}", size: normal_size, align: :center
          text "Patient: #{account_name}", size: normal_size, align: :center
          move_down 30
        end

        move_down 20

        bounding_box([0, cursor], width: 540) do
          text "Measurements", size: header_size, style: :bold
          move_down 10
          if @measurements&.any?
            table measurements_table, width: 540, cell_style: { size: normal_size } do
              style rows(0), style: :bold, background_color: "E8E8E8"
              style column(2), align: :right
            end
          else
            text "No measurements recorded.", size: normal_size, style: :italic
          end
        end

        move_down 30

        bounding_box([0, cursor], width: 540) do
          text "Diseases", size: header_size, style: :bold
          move_down 10
          if @diseases&.any?
            @diseases.each do |disease|
              text "• #{disease.predefined_disease.name} - #{disease.status}", size: normal_size
              if disease.diagnosed_at
                text "  Diagnosed: #{disease.diagnosed_at.strftime('%d %B %Y') if disease.diagnosed_at}",
                     size: 8
              end
            end
          else
            text "No diseases recorded.", size: normal_size, style: :italic
          end
        end

        move_down 30

        bounding_box([0, cursor], width: 540) do
          text "Medications", size: header_size, style: :bold
          move_down 10
          if @medications&.any?
            @medications.each do |med|
              text "• #{med.name} - #{med.dosage} (#{med.frequency})", size: normal_size
            end
          else
            text "No medications recorded.", size: normal_size, style: :italic
          end
        end

        move_down 30

        bounding_box([0, cursor], width: 540) do
          text "Treatments", size: header_size, style: :bold
          move_down 10
          if @treatments&.any?
            @treatments.each do |treatment|
              text "• #{treatment.name}", size: normal_size
              text "  Status: #{treatment.status}", size: 8
            end
          else
            text "No treatments recorded.", size: normal_size, style: :italic
          end
        end

        move_down 50
        text "Generated by Salus", size: 8, align: :center, style: :italic
      end.render
    end

    def generate_measurements_pdf(measurements)
      table_data = measurements_table_data(measurements)
      Prawn::Document.new do
        title_size = 20
        normal_size = 10

        text "Measurements Report", size: title_size, style: :bold, align: :center
        move_down 20

        if measurements.any?
          text "Total: #{measurements.count} measurements", size: normal_size
          move_down 10

          table table_data, width: 540, cell_style: { size: normal_size } do
            style rows(0), style: :bold, background_color: "E8E8E8"
            style column(2), align: :right
          end
        else
          text "No measurements recorded.", size: normal_size, style: :italic, align: :center
        end

        move_down 30
        text "Generated by Salus - #{Time.zone.today.strftime('%d %B %Y')}", size: 8, align: :center, style: :italic
      end.render
    end

    def measurements_table_data(measurements)
      header = %w[Type Value Date]
      rows = measurements.map do |m|
        [m.measurement_type.name.humanize, "#{m.value} #{m.measurement_type.unit.symbol}",
         m.measurement_date.strftime("%d %b %Y")]
      end
      [header] + rows
    end

    def generate_diseases_pdf(diseases)
      Prawn::Document.new do
        title_size = 20
        normal_size = 10

        text "Diseases Report", size: title_size, style: :bold, align: :center
        move_down 20

        if diseases.any?
          diseases.each do |disease|
            bounding_box([0, cursor], width: 540) do
              text "• #{disease.predefined_disease.name}", size: normal_size, style: :bold
              text "  Status: #{disease.status}", size: normal_size
              if disease.diagnosed_at
                text "  Diagnosed: #{disease.diagnosed_at.strftime('%d %B %Y') if disease.diagnosed_at}",
                     size: 8
              end
              text "  Notes: #{disease.notes}", size: 8 if disease.notes
              move_down 15
            end
          end
        else
          text "No diseases recorded.", size: normal_size, style: :italic, align: :center
        end

        move_down 30
        text "Generated by Salus - #{Time.zone.today.strftime('%d %B %Y')}", size: 8, align: :center, style: :italic
      end.render
    end

    def generate_medications_pdf(medications)
      table_data = medications_table_data(medications)
      Prawn::Document.new do
        title_size = 20
        normal_size = 10

        text "Medications Report", size: title_size, style: :bold, align: :center
        move_down 20

        if medications.any?
          table table_data, width: 540, cell_style: { size: normal_size } do
            style rows(0), style: :bold, background_color: "E8E8E8"
          end
        else
          text "No medications recorded.", size: normal_size, style: :italic, align: :center
        end

        move_down 30
        text "Generated by Salus - #{Time.zone.today.strftime('%d %B %Y')}", size: 8, align: :center, style: :italic
      end.render
    end

    def medications_table_data(medications)
      header = %w[Name Dosage Frequency Status]
      rows = medications.map do |m|
        [m.name, m.dosage || "-", m.frequency || "-", m.is_active ? "Active" : "Inactive"]
      end
      [header] + rows
    end

    def generate_treatments_pdf(treatments)
      Prawn::Document.new do
        title_size = 20
        normal_size = 10

        text "Treatments Report", size: title_size, style: :bold, align: :center
        move_down 20

        if treatments.any?
          treatments.each do |treatment|
            bounding_box([0, cursor], width: 540) do
              text "• #{treatment.name}", size: normal_size, style: :bold
              text "  Status: #{treatment.status}", size: normal_size
              text "  Description: #{treatment.description}", size: 8 if treatment.description
              move_down 15
            end
          end
        else
          text "No treatments recorded.", size: normal_size, style: :italic, align: :center
        end

        move_down 30
        text "Generated by Salus - #{Time.zone.today.strftime('%d %B %Y')}", size: 8, align: :center, style: :italic
      end.render
    end
  end
end
